package Bireysel____Denemeler;

public class Market_programi_konstraktir_Runner_Classi {

    public static void main(String[] args) {


        Market_programi_konstraktir obje=new Market_programi_konstraktir("elma",4);

    }//main
}


//  NOT:::::::::::  KALIP KLASTA VARIABLE OLUSTURMADAN KOSTRAKTIR OLUSTURDUM:
// BU KONSTRAKTIRDA ISLENECEK MALZELERI BENIM RUNNER KLASCTAN GONDERMEM GEREKIYOR
// SONRA GONDERDIGIM O MALZEMELER ILE NE YAPARSAN HANGI KODU YAZARSAN YAZ :
// ORDA YAPTIGIN ISLEMLERIN SONUCUNU DA SOUTLA KOSTRAKTIR BITMEDEN YAZDIR

// GENERATE ZAYDIRMA KOMUTU KONSTRAKTIR ICIN DEGILDI: ICERISINE YAZDIGINDA DA ZATEN KENDI DISINA ATIYOR
 // GENERATE KOMUTU RUNNER CLASSTA OLUSTURDUGUN OBJELERI YAZDIRMAK ICIN KULLANIRI : KALIP KLASSTA
// KULLANIRSIN:RUNNER CLASSTA SADECE  SAUT VAR:

//konstrakter lara new siz ulasilamiyor .